"""Init

Revision ID: 87914c3e7541
Revises: 
Create Date: 2023-04-28 06:56:18.774993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87914c3e7541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
